[package]
name = "excar"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
dirs = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }

